### ISSUE TITLE
デザイン制作

### ISSUE THREAD

**Issue by yuta-sksn** [Drop-in-Hachinohe/kodomo_syokudou#1]
FYI
* [すこやかこども食堂](https://kodomokafe.hp.peraichi.com/)

**Comment by YuukiIshibashi** [comment]
めちゃくちゃ雑にタタキを作成しましたmm
![子ども食堂 web](https://user-images.githubusercontent.com/20594454/230593605-81e9c1d9-23c9-47a7-8837-7d988e2e4f41.jpg)

**Comment by YuukiIshibashi** [comment]
修正
![子ども食堂 web_アートボード 1](https://user-images.githubusercontent.com/20594454/232666005-7fc66c60-c590-4724-879b-21b8a5ea6fc8.jpg)
![子ども食堂 web_アートボード 1 のコピー](https://user-images.githubusercontent.com/20594454/232666016-5b62237b-803f-4a3d-8aee-f6757fee15da.jpg)
